### ISSUE TITLE
Survey workflow

### ISSUE THREAD

**Issue by Satendra-SR** [ColoredCow/moodle-survey#4]
### Survey

**SL admin**
1. List of surveys should be visible - done
    1. Functionality - done
    2. UI cleanups - Pending
2. Filters - on list page - in-progress
    - [x] Dynamic - add the list of categories dynamically from the database
3. Create the survey - In progress
    1. General details - UI clean-ups
        - [x] Survey name
        - [x] Survey Category
        - [x] Survey description
    2. Questions & scores - in-progress
        - [x] Questions
        - [x] Question category
        - [x] Option and its score
        - [x] Add New questions, option and its score - clone functionality - Gaurav
    3. Interpretations - in-progress
        - [x] Question category
        - [x] From & to - interpretation score
        - [x] Interpreted as - text
        - [x] Add new range & interpretation - clone functionality - on-hold
    4. Validity - UI cleanups 
        - [x] Start date
        - [x] End date
    5. Access - in-progress
        - [x] Assign to schools
        - [x] Survey targets - 
            1. Teachers or students - open question whether one survey can be taken by teacher or students at the same time
        - [x] Access to Response
        - [x] Publish the survey
4. Edit and update the survey - In-progress
    - [x] Till we haven’t marked the survey as published, it will be draft
    - [x] Once the survey creation is completed, we will mark it published
    - [x] Initially, the survey will be marked as published 
    - [x] Once the start date reach, it will make as active
    - [x] Once the end date reached, it will marked as completed
5. Create/Edit survey categories - Pending - Low priority
6. Assign the survey to one or more schools - Pending
7. View responses - Analytics -  Pending - Research (Gaurav)
    - [ ] Users survey response
    - [ ] Fetch the response
    - [ ] Research on re-using the analytical capabilities of Moodle - feedback plugin capability

**School assignment** - To be cleaned up @Satendra-SR 
1. Counselor & principal access - Pending
    1. Assigning the surveys to students - Pending
        1. Counselor and Principal should be able to view the available survey 
        2. Counselor and Principal should be able to assign the survey to students 
    2. View the analysis of past surveys - Pending
        1. Not individual response but an overview of what have been the trends
2. Students & teacher - Pending
    1. Once assigned - 
        1. The students and teachers should be able top view the available survey
        2. The users (S & T) should be able to access the survey and take the part in active survey
    2. Past surveys
        1. The users should be able see the list of past survey
        2. The users should be able to see the past survey score
        3. The teachers should be able to see the insights of past survey response for students.

**Comment by Ayush8923** [comment]
These all feature are implemented and live on UAT. Closing this issue.
